export const RECIPES_LOADING = 'RECIPES_LOADING';
export const ADD_RECIPES = 'ADD_RECIPES';
export const RECIPES_FAILED = 'RECIPES_FAILED';

export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CATEGORY_FAILED = 'CATEGORY_FAILED';
